### ISSUE TITLE
Problems after install with Yarn - Modules cannot be found

### ISSUE THREAD

**Issue by kevinvhengst** [MagicTheGathering/mtg-sdk-typescript#1]
I wanted to play around for a bit with the SDK to learn TypeScript and React. I ran into some problems after running `yarn install mtgsdk-ts`. I can import the library like `import * as MTG from "mtgsdk-ts"` and in my editor I get all the required code completion.

But when compiling I get the following bunch of errors and warnings:

```
WARNING in ./node_modules/har-validator/node_modules/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/har-validator/node_modules/ajv/lib/async.js
 @ ./node_modules/har-validator/node_modules/ajv/lib/ajv.js
 @ ./node_modules/har-validator/lib/node4/promise.js
 @ ./node_modules/request/lib/har.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/mtgsdk-ts/out/Magic.js
 @ ./src/components/container.tsx
 @ ./src/index.tsx

WARNING in ./node_modules/har-validator/node_modules/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/har-validator/node_modules/ajv/lib/compile/index.js
 @ ./node_modules/har-validator/node_modules/ajv/lib/ajv.js
 @ ./node_modules/har-validator/lib/node4/promise.js
 @ ./node_modules/request/lib/har.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/mtgsdk-ts/out/Magic.js
 @ ./src/components/container.tsx
 @ ./src/index.tsx

WARNING in ./node_modules/har-validator/node_modules/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/har-validator/node_modules/ajv/lib/async.js
 @ ./node_modules/har-validator/node_modules/ajv/lib/ajv.js
 @ ./node_modules/har-validator/lib/node4/promise.js
 @ ./node_modules/request/lib/har.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/mtgsdk-ts/out/Magic.js
 @ ./src/components/container.tsx
 @ ./src/index.tsx

ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/Users/kevinvanhengst/Projects/mtg-card-finder/node_modules/request/lib'
 @ ./node_modules/request/lib/har.js 3:9-22
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/mtgsdk-ts/out/Magic.js
 @ ./src/components/container.tsx
 @ ./src/index.tsx

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/kevinvanhengst/Projects/mtg-card-finder/node_modules/forever-agent'
 @ ./node_modules/forever-agent/index.js 6:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/mtgsdk-ts/out/Magic.js
 @ ./src/components/container.tsx
 @ ./src/index.tsx

ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in '/Users/kevinvanhengst/Projects/mtg-card-finder/node_modules/tough-cookie/lib'
 @ ./node_modules/tough-cookie/lib/cookie.js 32:10-24
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/mtgsdk-ts/out/Magic.js
 @ ./src/components/container.tsx
 @ ./src/index.tsx

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/kevinvanhengst/Projects/mtg-card-finder/node_modules/tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 3:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/mtgsdk-ts/out/Magic.js
 @ ./src/components/container.tsx
 @ ./src/index.tsx

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/kevinvanhengst/Projects/mtg-card-finder/node_modules/forever-agent'
 @ ./node_modules/forever-agent/index.js 7:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/mtgsdk-ts/out/Magic.js
 @ ./src/components/container.tsx
 @ ./src/index.tsx

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/kevinvanhengst/Projects/mtg-card-finder/node_modules/tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 4:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/mtgsdk-ts/out/Magic.js
 @ ./src/components/container.tsx
 @ ./src/index.tsx

ERROR in [at-loader] ./src/components/container.tsx:4:22
    TS2307: Cannot find module 'mtgsdk-ts'.

ERROR in [at-loader] ./src/components/container.tsx:22:41
    TS7006: Parameter 'results' implicitly has an 'any' type.
```

All I do is trying out the code following example:

```
MTG.Cards.where({name: "Nicol"}).then(results => {
  for (const card of results) console.log(card.name);
});
```

I am using the following dependencies:

```
"dependencies": {
    "mtgsdk-ts": "^1.1.2",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "source-map-loader": "^0.2.3"
  },
  "devDependencies": {
    "@types/react": "^16.0.38",
    "@types/react-dom": "^16.0.4",
    "awesome-typescript-loader": "^3.5.0",
    "http-server": "^0.11.1",
    "ts-loader": "^4.0.0",
    "typescript": "^2.7.2",
    "webpack": "3.11.0"
  }
```

And my tsconfig.json is as follows:

```
{
  "compilerOptions": {
      "outDir": "./dist/",
      "sourceMap": true,
      "noImplicitAny": true,
      "module": "commonjs",
      "target": "es5",
      "jsx": "react"
  },
  "include": [
      "./src/**/*"
  ]
}
```

Since it is mostly complaining about the fact that modules cannot be found, has this anything to do with `commonjs`? It explicitly says `TS2307: Cannot find module 'mtgsdk-ts'.` while in my code it recognizes it fine.

**Comment by Yuudaari** [comment]
I don't think this would be an issue with this sdk, but I'm not sure what the issue is, I've never seen anything like the errors you're getting. Is your repository public? I would have to experiment with it on my end to figure out what's happening

**Comment by kevinvhengst** [comment]
I've pushed the changes that causes this problems to a test branch: [mtg-card-finder](https://github.com/kevinvhengst/mtg-card-finder/tree/bug/mtgsdk)

I didn't add a Readme yet, but you have to run webpack first since I don't add the compiled JS into my repo. So first run `yarn run webpack` to compile. I've added the `http-server` package so after compiling you can run `yarn run run` and it will run the application on `localhost:8080`

Thanks for your time 👍

**Comment by Yuudaari** [comment]
I'm not sure where the issue is because I honestly don't know the first thing about Yarn or Webpack, and I've never seen `awesome-typescript-loader` either. However, just running `tsc` on your repository works, so it seems like the issue is with one of them. Maybe you have to list this module as a dependency somewhere else? There's not much I can think of as they're not technologies I'm familiar with. At some point I can go through this more thoroughly and learn them, but it probably won't be for a while as work is a bit busy right now.

Now that I think about it tho, are you trying to import the sdk from the client (browser)? Is that what you're doing with Webpack? Maybe I don't understand fully.... if that is what you're doing, I don't think that would work. The whole package would need to be rewritten to support that. It's intended to be used from a Node.js environment.

**Comment by kevinvhengst** [comment]
What Webpack does is bundle modules and make it suitable to serve to the browser. Yarn is just another package manager like NPM. It's proven to be quite a bit faster than NPM though. 

I am in no need of a back-end for my application, since everything is presented with React and I get all my data from MTG API. So yes, I am not using any Node.js for this application because there is simply no need to. 

Thanks for your time anyway! I will implement my own TypeScript wrapper for the API then and might reuse your type definitions with your approval :-)

In the future when you might want to add client side support and you might need a helping hand I am willing to help out. Still in the learning fase of TypeScript but I might be able to take some work from your hands.

**Comment by adback03** [comment]
So I have experience with Webpack and decided to take a peak. One thing you need to add to your webpack config is this section:

```
node: {
    console: true,
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
```

The whole webpack looks like this now:

```
module.exports = {
  entry: "./src/index.tsx",
  output: {
    filename: "bundle.js",
    path: __dirname + "/dist"
  },
  watch: true,

  // Enable sourcemaps for debugging weback's output.
  devtool: "source-map",

  resolve: {
    // Add .ts and .tsx and resolvable extensions
    extensions: [".ts", ".tsx", ".js", ".json"]
  },

  module: {
    rules: [
      { test: /\.tsx?$/, loader: "awesome-typescript-loader" },

      // All output .js files will have any sourcemaps re-processed by 'source-map-loader'
      { enforce: "pre", test: /\.ts$/, loader: "source-map-loader" }
    ]
  },

  // When importing a module whose path matches one of the following, just
  // assume a corresponding global variable exists and use that instead.
  // This is important because it allows us to avoid bundling all of our
  // dependencies, which allows browsers to cache those libraries between builds.
  externals: {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  node: {
    console: true,
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
}
```

This resolves the errors, though I still get the warnings. I was able to use the SDK like this then:

```
import * as React from "react";
import * as ReactDOM from "react-dom";

import * as Magic from "mtgsdk-ts";

type SearchFormProps = {
	searchValue: string,
	search: () => void
	setSearchValue: (searchValue: string) => void
}

type SearchFormState = {

}

export class SearchForm extends React.Component<SearchFormProps, {}> {
	constructor(props: SearchFormProps) {
		Magic.Cards.find("08618f8d5ebdc0c4d381ad11f0563dfebb21f4ee").then(result => console.log(result.name));
		super({
			searchValue: '',
			search: (): void => { },
			setSearchValue: (searchValue: string): void => { }
		})
	}

	render() {
		return (
			<div>
				<label htmlFor="searchValue">Card name:</label>
				<input type="text" name="searchValue" className="searchValue" onChange={(e) => this.props.setSearchValue(e.currentTarget.value)} />
				<button name="Search" value="" onClick={() => this.props.search()}>Search</button>
			</div>
		)
	}
}
```

Haven't had a chance to look more into the warnings, but the app will at least compile and run!

**Comment by Yuudaari** [comment]
Wow, I can't believe that webpack can do this kind of thing. I am thoroughly impressed. Thanks for looking into this!

**Comment by kevinvhengst** [comment]
Thanks a lot! I am new to Webpack myself so I was not aware of this functionality. I will look further into the warnings and report back if I find a solution.
